<?php require('template/header.phtml') ?>
/**
 * Created by PhpStorm.
 * User: Tom
 * Date: 30/10/2016
 * Time: 01:58
 */
<h1>Zeus</h1>
<p>"Our System is designed so you can watch exactly what everyone else is watching, by using a voting system to decided which channels are put on next."</p>
<p>"The stream also features chat which you can see how people find the chosen program, with this chat we have an algorithm that detects how well a choice is received"</p>
<p>"People who voted for a well-received program are given more reputation which increases their voting power in the future"</p>
<p>"Using historical data we can also see which types of shows people like and then suggest that they enter rooms which are shared by people with similar preferences"</p>