<?php require('template/header.phtml');
    $basket = $_SESSION['basket'];
    //Checks that POST isn't empty
    if(!empty($_POST)) {
        //Checks whether it's to Delete DVD or Rent DVD
        if(!empty($_POST['delete_dvd'])) {
            $key = 0;
            $array = array_keys($basket);
            foreach ($basket as $item) {
                //Removes the DVD from the Basket
                if ($item[0] == $_POST['delete_dvd']) {
                    unset($basket[$array[$key]]);
                    $_SESSION['basket'] = $basket;
                }
                $key++;
            }
            header("Location: basket.php");
            die();
        }
        if(!empty($_POST['rent_dvd'])) {
            $key = 0;
            $array = array_keys($basket);
            foreach ($basket as $item) {
                //Rents the DVD, assigning the User ID and changing the fact it's Rented.
                $DVD = new DVD($item[0]);
                if(!($DVD->data()->rented == 1)) {
                    $DVD->update("UPDATE dvd_details SET rented='1', user_id='" . $user->data()->id . "' WHERE id=" . $DVD->data()->id . "");
                }
                unset($basket[$array[$key]]);
                $_SESSION['basket'] = $basket;
                $key++;
            }
            header("Location: index.php");
            die();
        }
    }

if (empty($basket)) { ?>
    <h2>Your Basket is Empty</h2>
<?php } elseif (!empty($basket)) { ?>
    <h2>Your Basket</h2>
<?php }
$total_price = 0;
foreach ($basket as $item) {
    //Display the details of the DVD for the Basket.
    $DVD = new DVD($item[0]);
    $data = $DVD->data();
    $Price = new Price_Band($data->price_band);
    $total_price = $total_price + $Price->data()->price;
?>
        <div Class="film_details col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
            <div class="col-xs-12 col-sm-4 col-md-4 col-lg-2">
                <div class="thumbnail">
                    <a href="dvds.php?id=<?php echo $data->id ?>"><img src="<?php echo $data->picture;?>" class="poster-image" alt="..."></a>
                </div>
            </div>
            <div class="col-xs-12 col-sm-8 col-md-8 col-lg-10">
                <a href="dvds.php?id=<?php echo $data->id ?>"><h2><?php echo $data->title . "(" . $data->year_of_release . ")"; ?></h2></a>
                <h4>Description</h4>
                <p><?php echo $data->synopsis; ?></p>
                <p>Price: &pound;<?php echo $Price->getPrice(); ?></p>
                <p><form autocomplete="off" method="POST" action="" ><button type="submit" type="button" class="btn btn-primary-outline">Remove from basket</button><input type="hidden" name="delete_dvd" value="<?php echo $data->id ?>"></form></p>
            </div>
        </div>
<?php }
if (!empty($basket)) {
//Display the Total Price of all the DVDs and Rent the DVDs
?>
<p><h3 class="pull-left">Total Price: &pound;<?php echo number_format($total_price, 2, '.', ''); ?></h3><form autocomplete="off" method="POST" action="" class="pull-right" ><button type="submit" type="button" class="btn btn-primary-outline">Rent the DVDs</button><input type="hidden" name="rent_dvd" value="rent"></form></p>

<?php } require('template/footer.phtml'); ?>
