<?php require('template/header.phtml');
    //Checks that POST isn't empty
    if(!empty($_POST)) {
        if(!empty($_POST['DVD_id'])) {
            //If DVDID is posted then the DVD ID gets added to the basket.
            addToBasket($_POST['DVD_id']);
            header("Location: basket.php");
            die();
        } elseif (!empty($_POST['return'])) {
            //Returns the DVD changing the DVD details to 0 for user_id and Rented.
                $DVD = new DVD($_POST['return']);
                $DVD->update("UPDATE dvd_details SET rented='0', user_id='0' WHERE id=" . $DVD->data()->id . "");
            header("Location: index.php");
            die();
        }
    }

    //Display details of the DVD.
?>
    <div Class="film_details col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-2">
            <div class="thumbnail">
                <img src="<?php echo $data->picture;?>" class="poster-image" alt="...">
            </div>
        </div>
        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-10">
            <h2><?php echo $data->title . "(" . $data->year_of_release . ")"; ?></h2>
            <p><?php echo $data->synopsis; ?></p>
            <p>Genre: <?php echo $theDVD->getGenre(); ?></p>
            <p>Director: <a href=search.php?search=<?php echo urlencode($director->data()->name); ?>&type=director_id><?php echo $director->data()->name; ?></a></p>
            <p>Starring: <?php echo $theDVD->getCast(); ?></p>
            <p>Studio: <a href=search.php?search=<?php echo urlencode($data->studio); ?>&type=studio><?php echo $data->studio; ?></a></p>
            <p>Price: &pound;<?php echo $price_band->getPrice(); ?></p>
            <?php //Gets the Rent Details and displays the correct buttons ?>
            <p><?php echo $theDVD->rentDetails($user); ?></p>
        </div>
    </div>
    <div class="film-carousel col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h2>Latest Films</h2>
        <div class="row">
        <?php $newDVD = new DVD();
        $results = $newDVD->getLatest();
        //Displays the Latest DVDS to be added to the database.
        foreach($results as $result) {
            $latestDVD = new DVD($result->id); ?>
            <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                <a href="dvds.php?id=<?php echo $latestDVD->data()->id ?>" class="thumbnail">
                    <img src="<?php echo $latestDVD->data()->picture ?>" class="poster-image" alt="...">
                </a>
            </div>
        <?php } ?>
        </div>
    </div>
<?php require('template/footer.phtml') ?>