<?php require('template/header.phtml') ?>
<div class="container">
        <div class="row">
            <div class="col-md-9 col-sm-12">
                <div style="background-color: #dddddd;">
                    <div class="video-container"><iframe width="560" height="315" src="https://www.youtube.com/embed/EI0ib1NErqg" frameborder="0" allowfullscreen></iframe></div>
                </div>
            </div>
            <div class="col-md-3 col-sm-12">
                <div style="background-color: #1c1c1c;">
                    <div id="wrapper">                         
                        <div id="chatbox">
                            <span>Chat text</span><br>
                            <span>Chat text</span><br>
                            <span>Chat text</span><br>
                            <span>Chat text</span><br>
                            <span>Chat text</span><br>
                            <span>Chat text</span><br>
                            <span>Chat text</span><br>
                            <span>Chat text</span><br>
                            <span>Chat text</span><br>
                            <span>Chat text</span><br>
                            <span>Chat text</span><br>
                            <span>Chat text</span><br>
                        </div>
                         
                        <form name="message" action="">
                            <input type="submit" name="submit" value="Submit" style="float: right" />
                            <div style="overflow: hidden; padding-right: .5em;">
                                <input type="text" name="msg" style="width: 100%;" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="row" style="margin-top: 20px;margin-bottom: 20px">
            <div class="col-sm-4">
                Time left in current slot: 15:00:10
            </div>
            <div class="col-sm-4">
                Current time 17:45
            </div>
            <div class="col-sm-4">
                Time left to vote: 10:00:09
            </div>
        </div>

        <div class="row" style="padding-left: 10%;padding-right: 10%">
            <?php foreach ($view->options as $option) {
                ?>
                <div class="col-md-3 col-sm-12 padding10">
                    <a href="/" class="btn btn-primary"><img src="<?php echo getPoster($option->getShowTitle()); ?>" style="width: 150px" ></a>
                    <br/>
                    <?php echo $option->getShowTitle() ?></br>
                </div>
                <?php
            } ?>
        </div>

        <hr/>

        <div class="row">
            <div class="col-sm-12 padding10">
                <p>Game Of Thrones</p>
                <div class="progress">
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                        <span class="sr-only">60%</span>
                    </div>
                </div>
            </div>
        </div>
        <script>
            setInterval( function() { 
                $.ajax({
                    type: "POST"
                , url: "Ajax_folder/poll_percentages.php"
                , data: "id=453&action=test" 
                , beforeSend: function(){

                } 
                , complete: function(){ 
                }  
                , success: function(data){
                    $(".progress-bar-success").css('width', data);;       
                }});
            }, 2000);
        </script>

        <div class="row">
            <div class="col-sm-12 padding10">
                <p>Great British Bake Off</p>
                <div class="progress">
                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 20%;">
                        <span class="sr-only">20%</span>
                    </div>
                </div>
            </div>
        </div>
        <script>
            setInterval( function() { 
                $.ajax({
                    type: "POST"
                , url: "Ajax_folder/poll_percentages.php"
                , data: "id=453&action=test" 
                , beforeSend: function(){

                } 
                , complete: function(){ 
                }  
                , success: function(data){
                    $(".progress-bar-info").css('width', data);;       
                }});
            }, 2000);
        </script>

        <div class="row">
            <div class="col-sm-12 padding10">
                <p>Top Gear</p>
                <div class="progress">
                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 9%;">
                        <span class="sr-only">9%</span>
                    </div>
                </div>
            </div>
        </div>
        <script>
            setInterval( function() { 
                $.ajax({
                    type: "POST"
                , url: "Ajax_folder/poll_percentages.php"
                , data: "id=453&action=test" 
                , beforeSend: function(){

                } 
                , complete: function(){ 
                }  
                , success: function(data){
                    $(".progress-bar-warning").css('width', data);;       
                }});
            }, 2000);
        </script>

        <div class="row">
            <div class="col-sm-12 padding10">
                <p>Premier League</p>
                <div class="progress">
                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 1%;">
                        <span class="sr-only">1%</span>
                    </div>
                </div>
            </div>
        </div>
        <script>
            setInterval( function() { 
                $.ajax({
                    type: "POST"
                , url: "Ajax_folder/poll_percentages.php"
                , data: "id=453&action=test" 
                , beforeSend: function(){

                } 
                , complete: function(){ 
                }  
                , success: function(data){
                    $(".progress-bar-danger").css('width', data);;       
                }});
            }, 2000);
        </script>

        <hr/>

        <div style="margin-bottom: 20px">
            Copyright 2016 &copy; 3 Of A Kind All Rights Reserved
        </div>

    </div>
<?php require('template/footer.phtml') ?>