<?php require('template/header.phtml') ?>
<div class="container">
        <div class="row">
            <div class="col-md-9 col-sm-12" style="padding: 2%">
                <div style="background-color: #dddddd; height: 70%">
                    <br/>
                </div>
            </div>
            <div class="col-md-3 col-sm-12">
                One of three columns
            </div>
        </div>

        <div class="row" style="margin-top: 20px;margin-bottom: 20px">
            <div class="col-sm-4">
                Time left in current slot: 15:00:10
            </div>
            <div class="col-sm-4">
                Current time 17:45
            </div>
            <div class="col-sm-4">
                Time left to vote: 10:00:09
            </div>
        </div>

        <div class="row" style="padding-left: 10%;padding-right: 10%">
            <div class="col-md-3 col-sm-12 padding10">
                <a href="/" class="btn btn-primary"><img src="<?php echo getPoster("Game of Thrones"); ?>" style="width: 150px" ></a>
                <br/>
                Game of Thrones</br>
                Sky Atlantic
            </div>
            <div class="col-md-3 col-sm-12 padding10">
                <a href="/" class="btn btn-primary" style="height: inherit"><img src="<?php echo getPoster("The Great british Bake Off"); ?>" style="width: 150px; " ></a>
                <br/>
                The Great British Bake Off</br>
                BBC One
            </div>
            <div class="col-md-3 col-sm-12 padding10">
                <a href="/" class="btn btn-primary" style="height: inherit"><img src="<?php echo getPoster("Top Gear"); ?>" style="width: 150px; " ></a>
                <br/>
                Top Gear</br>
                Dave
            </div>
            <div class="col-md-3 col-sm-12 padding10">
                <a href="/" class="btn btn-primary" style="height: inherit"><img src="<?php echo getPoster("Premier League"); ?>" style="width: 150px; " ></a>
                <br/>
                Premier League</br>
                Sky Sports
            </div>
        </div>

        <hr/>

        <div class="row">
            <div class="col-sm-12 padding10">
                <p>Game Of Thrones</p>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                        <span class="sr-only">60%</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 padding10">
                <p>Great British Bake Off</p>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%;">
                        <span class="sr-only">20%</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 padding10">
                <p>Top Gear</p>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="9" aria-valuemin="0" aria-valuemax="100" style="width: 9%;">
                        <span class="sr-only">9%</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 padding10">
                <p>Premier League</p>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="1" aria-valuemin="0" aria-valuemax="100" style="width: 1%;">
                        <span class="sr-only">1%</span>
                    </div>
                </div>
            </div>
        </div>

        <hr/>

        <div style="margin-bottom: 20px">
            Copyright 2016 &copy; 3 Of A Kind All Rights Reserved
        </div>

    </div>

<?php require('template/footer.phtml') ?>