<?php require('template/header.phtml') ?>
<div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div style="background-color: #dddddd;">
                    <div class="video-container"><iframe width="560" height="315" src="https://www.youtube.com/embed/EI0ib1NErqg" frameborder="0" allowfullscreen></iframe></div>
                </div>
            </div>            
        </div>

        <div class="row" style="margin-top: 20px;margin-bottom: 20px">
            <div class="col-sm-4">
                Time left in current slot: 15:00:10
            </div>
            <div class="col-sm-4">
                You are watching: <?php echo $view->lastVote->getShowTitle(); ?> on <?php echo $view->lastVote->getChannel()->getName(); ?>
            </div>
            <div class="col-sm-4">
                Time left to vote: 10:00:09
            </div>
        </div>

        <div class="row" style="padding-left: 10%;padding-right: 10%">
            <?php foreach ($view->options as $option) {
                ?>
                <div class="col-md-3 col-sm-12 padding10">
                    <a class="btn btn-primary<?php echo " " . $option->getChannel()->getId() . "-click"; ?>"><img src="<?php echo getPoster($option->getShowTitle()); ?>" style="width: 150px" onError="this.onerror=null;this.src='<?php echo getPoster("Top Gear"); ?>';"></a>
                    <br/>
                    <?php echo $option->getShowTitle(); ?></br>
                    <?php echo $option->getChannel()->getName(); ?></br>
                </div>
                <script>
                    $("<?php echo "." . $option->getChannel()->getId() . "-click"; ?>").click(function() { 
                        $.ajax({
                            type: "POST"
                        , url: "Ajax_folder/vote_made.php?channelid=<?php echo $option->getChannel()->getId(); ?>&blockid=<?php echo $view->block; ?>&userid=<?php echo $user->data()->id; ?>"
                        , beforeSend: function(){
                        } 
                        , complete: function(){ 
                        }  
                        , success: function(){       
                        }});
                    });
                </script>
                <?php
            } ?>
        </div>

        <hr/>

        <div class="row">
            <div class="col-sm-12 padding10">
                <p><?php echo $view->options[0]->getShowTitle(); ?></p>
                <div class="progress">
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                        <span class="sr-only">60%</span>
                    </div>
                </div>
            </div>
        </div>
        <script>
            setInterval( function() { 
                $.ajax({
                    type: "POST"
                , url: "Ajax_folder/poll_percentages.php?channelid=<?php echo $view->options[0]->getChannel()->getId(); ?>&blockid=<?php echo $view->block; ?>"
                , beforeSend: function(){

                } 
                , complete: function(){ 
                }  
                , success: function(data){
                    $(".progress-bar-success").css('width', data);;       
                }});
            }, 1000);
        </script>

        <div class="row">
            <div class="col-sm-12 padding10">
                <p><?php echo $view->options[1]->getShowTitle(); ?></p>
                <div class="progress">
                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                        <span class="sr-only">20%</span>
                    </div>
                </div>
            </div>
        </div>
        <script>
            setInterval( function() { 
                $.ajax({
                    type: "POST"
                , url: "Ajax_folder/poll_percentages.php?channelid=<?php echo $view->options[1]->getChannel()->getId(); ?>&blockid=<?php echo $view->block; ?>"
                , beforeSend: function(){

                } 
                , complete: function(){ 
                }  
                , success: function(data){
                    $(".progress-bar-info").css('width', data);;       
                }});
            }, 1000);
        </script>

        <div class="row">
            <div class="col-sm-12 padding10">
                <p><?php echo $view->options[2]->getShowTitle(); ?></p>
                <div class="progress">
                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                        <span class="sr-only">9%</span>
                    </div>
                </div>
            </div>
        </div>
        <script>
            setInterval( function() { 
                $.ajax({
                    type: "POST"
                , url: "Ajax_folder/poll_percentages.php?channelid=<?php echo $view->options[2]->getChannel()->getId(); ?>&blockid=<?php echo $view->block; ?>"
                , beforeSend: function(){

                } 
                , complete: function(){ 
                }  
                , success: function(data){
                    $(".progress-bar-warning").css('width', data);;       
                }});
            }, 1000);
        </script>

        <div class="row">
            <div class="col-sm-12 padding10">
                <p><?php echo $view->options[3]->getShowTitle(); ?></p>
                <div class="progress">
                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                        <span class="sr-only">1%</span>
                    </div>
                </div>
            </div>
        </div>
        <script>
            setInterval( function() { 
                $.ajax({
                    type: "POST"
                , url: "Ajax_folder/poll_percentages.php?channelid=<?php echo $view->options[3]->getChannel()->getId(); ?>&blockid=<?php echo $view->block; ?>"
                , beforeSend: function(){

                } 
                , complete: function(){ 
                }  
                , success: function(data){
                    $(".progress-bar-danger").css('width', data);;       
                }});
            }, 1000);
        </script>

        <hr/>

        <div style="margin-bottom: 20px">
            Copyright 2016 &copy; 3 Of A Kind All Rights Reserved
        </div>

    </div>
<?php require('template/footer.phtml') ?>