<?php require('template/header.phtml') ?>
    <div class="film-carousel">
        <h2>Results for the Search "<?php echo sanitize($_GET['search']); ?>"</h2>
        <div class="row">
        <?php //Displays each DVD from the Search Array.
            foreach($searched as $result) { ?>
            <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                <a href="dvds.php?id=<?php echo $result->id ?>" class="thumbnail">
                    <img src="<?php echo $result->picture; ?>" class="poster-image" alt="...">
                </a>
            </div>
        <?php } ?>
         </div>
    </div>

<?php require('template/footer.phtml') ?>