<?php require('template/header.phtml') ?>
<div class="container">
    <div class="col-md-12 col-xs-12 col-centered">
        <section>
            <h2 class="text-center padding-10">Update User Settings</h2>
            <?php
            //Checks that POST isn't empty
            if(!empty($_POST)) {
                $check = new Check();
                //Update Account Details
                if($_POST['update_details'] === 'account') {
                    //Performs the Checks on the Submitted form for Settings
                    $check->required($_POST['email'], "Email");
                    $check->required($_POST['fullname'], "Fullname");
                    //Checks if the Check is passed
                    if ($check->passed()) {
                        //Sets up and updates the details of the user.
                        try {
                            $email = sanitize($_POST['email']);
                            $fullname = sanitize($_POST['fullname']);
                            $user->update("UPDATE users SET email='" . $email . "', fullname='" . $fullname . "' WHERE id=" . $user->data()->id . "");
                            header("Location: settings.php");
                            die();
                        } catch (Exception $e) {
                            die($e->getMessage());
                        }

                    } else {
                        foreach ($check->errors() as $error) {
                            echo '<div style="padding-bottom: 10px;"><div class="alert alert-danger no-border-radius no-margin" role="alert">' . $error . '</div></div>';
                        }
                    }
                    //Update Password Details
                } elseif($_POST['update_details'] === 'password') {
                    //Performs the Checks on the Submitted form for Settings
                    $check->required($_POST['currentpassword'], "Current Password");
                    $check->required($_POST['newpassword'], "New Password");
                    $check->required($_POST['repeatpassword'], "Repeat New Password");
                    $check->matches($_POST['newpassword'], $_POST['repeatpassword'], "Passwords");
                    //Checks if the Check is passed
                    if ($check->passed()) {
                        //Sets up and updates the password of the user.
                        try {
                            if(encrypt($_POST['currentpassword'], $user->data()->salt) !== $user->data()->password) {
                                echo '<div style="padding-bottom: 10px;"><div class="alert alert-danger no-border-radius no-margin" role="alert">Your Current Password is wrong</div></div>';
                            } else {
                                $salt = salt(32);
                                $password = encrypt($_POST['newpassword'], $salt);
                                $user->update("UPDATE users SET password='" . $password . "', salt='" . $salt . "' WHERE id=" . $user->data()->id . "");
                                header("Location: settings.php");
                                die();
                            }
                        } catch (Exception $e) {
                            die($e->getMessage());
                        }

                    } else {
                        foreach ($check->errors() as $error) {
                            echo '<div style="padding-bottom: 10px;"><div class="alert alert-danger no-border-radius no-margin" role="alert">' . $error . '</div></div>';
                        }
                    }
                }
            }
            ?>
            <form autocomplete="off" method="POST" action="" class="padding-10 centre">
                <div class="col-lg-6 padding-10"><input type="text" class="form-control input-lg" name="email" placeholder="Email" value="<?php echo $user->data()->email; ?>" required></div>
                <div class="col-lg-6 padding-10"><input type="text" class="form-control input-lg" name="fullname" placeholder="Fullname" value="<?php echo $user->data()->fullname; ?>" required></div>                
                <div class="padding-10">
                    <input type="hidden" name="update_details" value="account">
                    <button type="submit" class="padding-10 btn btn-success pull-right">Update</button>
                </div>
            </form>

            <form autocomplete="off" method="POST" action="" class="padding-10 centre">
                <div class="col-lg-12 padding-10"><input type="password" class="form-control input-lg" name="currentpassword" placeholder="Current Password" required></div>
                <div class="col-lg-6 padding-10"><input type="password" class="form-control input-lg" name="newpassword" placeholder="New Password" required></div>
                <div class="col-lg-6 padding-10"><input type="password" class="form-control input-lg" name="repeatpassword" placeholder="Re-Enter New Password" required></div>
                <div class="padding-10">
                    <input type="hidden" name="update_details" value="password">
                    <button type="submit" class="padding-10 btn btn-success pull-right">Update Password</button>
                </div>
            </form>
        </section>
    </div>
</div>

<?php require('template/footer.phtml') ?>
